language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run test:coverage
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  hackernews_clone_token: $hackernews_clone_token
  local_dir: build
  on:
    branch: master