language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  # Run format check
  - npm run format
  # Run linting check
  - npm run lint
  # Run test
  - npm test
  # Run test coverage
  - npm run test:coverage
  # Create build
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $hackernews_clone_token
  local_dir: build
  keep_history: true
  on:
    branch: master
